---
title: "PlotlyExample"
author: "Edén Sorolla"
date: "15/8/2020"
output: html_document
---

```{r setup, echo = FALSE, eval = FALSE, message = FALSE, results = FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, echo = FALSE, warning = FALSE, message = FALSE}
library(plotly)
library(tidyr)
library(ggplot2)
library(magrittr) ## In order to be able to use piping ( %>% )
library("readxl")
df1 <- read_excel("covid_19_data_switzerland-phase2.xlsx")
df2 <- read.csv("ch.csv", header = TRUE)
df2 <- df2[1:27,]

name <- df2$admin[-c(16)]

vecAux <- name[order(name)]

name <- vecAux
name[2] <- vecAux[3]
name[3] <- vecAux[2]
name[4] <- vecAux[6]
name[5] <- vecAux[4]
name[6] <- vecAux[5]
name[18] <- vecAux[19]
name[19] <- vecAux[18]
name[23] <- vecAux[24]
name[24] <- vecAux[23]
name[25] <- vecAux[26]
name[c(8,10,13,26)] <- c("Geneve", "Graubunden", "Neuchatel", "Zurich") ## we remove the accents

vec <- colnames(df1)[2:27]
df2 <- df2[order(df2$admin),]

df2 <- df2[-c(22),]

df2$admin[1] <- vec[1]
df2$admin[2] <- vec[3]
df2$admin[3] <- vec[2]
df2$admin[4] <- vec[5]
df2$admin[5] <- vec[6]
df2$admin[6] <- vec[4]
df2$admin[7:17] <- vec[7:17]
df2$admin[18] <- vec[19]
df2$admin[19] <- vec[18]
df2$admin[20:22] <- vec[20:22]
df2$admin[23] <- vec[24]
df2$admin[24] <- vec[23]
df2$admin[25] <- vec[26]
df2$admin[26] <- vec[25]

df2 <- df2[order(df2$admin),]

## We impute the missing values to zero:
for (j in 1:length(df1)){df1[is.na(df1[,j]),j] <- 0}

## We create the new dataframe with the Covid-19 cases on 14th August 2020:
infected <- matrix(apply(df1[, -c(1,28)], 2, max), ncol=1)
newDF <- data.frame(lat = df2$lat, lng = df2$lng, region = df2$admin, admin = name)
newDF <- cbind(newDF, infected)

## We get the data tidy and calculate the accumulated number of infections for each region:
df1New <- gather(df1,region, infected, AG:ZH)
df1New <- df1New %>%
    group_by(region) %>%
        mutate(accumulated.infected = cumsum(infected))
```

## Plotly Example

We present the cumulative number of infected people with Covid-19 in the different regions from Switzerland till 14th August.

```{r, echo = FALSE, warning = FALSE, message = FALSE, fig.width = 9, fig.height = 7}
fig <- df1New %>%
  plot_ly(
    x = ~region, 
    y = ~accumulated.infected,
    frame = ~Date,
    type = "bar",
    mode = "markers"
  )
fig <- fig %>% layout(
    xaxis = list(
      type = "lin"
    ),
    yaxis = list(
        type = "lin",
        title = "Cumulative number of infected people"
    )
  )

fig

```